### PR TITLE
Refresh indicator & update library

### PR DESCRIPTION
**Pull request by iamutaki**
i have add small feature (refresh indicator) to refresh content.

### CODE REVIEW

**Comment by iamutaki** [comment]
bump @SAGARSURI

**Review by SAGARSURI — APPROVED** [review]

**Comment by SAGARSURI** [comment]
@cacing69 can you move this to a separate branch.

**Comment by iamutaki** [comment]
oke @SAGARSURI, i will move this to branch `feature/refresh-indicator` on my fork, and what will be merge ?

**Comment by SAGARSURI** [comment]
Plan is to keep it as separate branch because my first two articles are based on the master branch code. If I merge the change it might change the scope of the content and people will get confused.

So all new features will come as a new branch like I did for DI, Testing and Pagination.

**Comment by iamutaki** [comment]
but what branch will be choose for my commit @SAGARSURI

**Comment by SAGARSURI** [comment]
Once you raise a PR with separate branch. I will create v2 of the master branch and merge all the new features into it.

**Pull request closed without merging**
